version: "3.3"
services:
//===========================================
  nginx:
    build: 
    ports:
      -
    volumes:
      -
//===========================================
  mariadb:
    image:
    volumes:
      -
    networks:
      -
//===========================================
  wordpress:
  