version: "3.3"
services:
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    - ./wp-config.php:/var/www/html/wordpress/wp-config.php
    networks:
    - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose:
    - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/wmonacho/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/wmonacho/data/mariadb

networks:
  inception:
    driver: bridge
