FROM: debian:buster
RUN: launches the commands (update, installation of nginx pe)
ENV: define env variables
EXPOSE: exhibits container ports
VOLUME: definition of volumes
COPY: copy elements between host and container
ENTRYPOINT: master process