FROM	debian:buster

RUN :	apt-get install -y

RUN :	apt-get update -y

RUN :	apt-get install -y nginx

RUN :	apt-get instal -y openssl
ENV: define env variables
EXPOSE: exhibits container ports
VOLUME: definition of volumes
COPY: copy elements between host and container
ENTRYPOINT: master process